### ISSUE TITLE
Great stuff!

### ISSUE THREAD

**Issue by GAZ082** [mattmattmatt/node-red-contrib-yeelight-compat-hue#4]
Love it's simplicity. Do you happen to have some color sequence functions to use?

**Comment by mattmattmatt** [comment]
Thanks for the compliment! 🙏 
I'm not sure I understand your question around "color sequence functions" – what exactly are you looking for?

**Comment by GAZ082** [comment]
You know, something like party colors, police headlights, etc. Colors in sequences.

**Comment by mattmattmatt** [comment]
Ah, you mean preset flows? There are none in this package, it only provides the basic functionality to make advances color functions easy to implement with Node-RED.
It should be simple however to create and publish some preset flows yourself – just a few JSON template nodes, a few timers and a Yeelight node should solve that for you. If I get some time I might play around with that. Until then, this package should provide you with all the tools to take control of your Yeelight for all purposes.
