### ISSUE TITLE
recover from power failure

### ISSUE THREAD

**Issue by davehun** [mattmattmatt/node-red-contrib-yeelight-compat-hue#5]
If the power is removed from a yeelight and then a command sent it gets stuck:
    `(node:20727) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: timeout`
This takes a long time.
powering up the yeelight again the console shows that the light has connected multiple times:
     `17 Jan 21:55:03 - [info] [yeelight-compat-hue-config:bedroom] Connecting to Yeelight 192.168.254.108:55443
     17 Jan 21:55:04 - [info] [yeelight-compat-hue-config:bedroom] Connected to 192.168.254.108:55443
    17 Jan 21:55:04 - [info] [yeelight-compat-hue-config:bedroom] Connecting to Yeelight 192.168.254.108:55443
    17 Jan 21:55:04 - [info] [yeelight-compat-hue-config:bedroom] Connected to 192.168.254.108:55443`
the state of the node in node-red is red with a connection error: undefined text.

**Comment by mattmattmatt** [comment]
Thank you, I'll verify and see how this could be handled better.

It might take a few days for me to get to this, but thank you for the report. 👍

**Comment by mattmattmatt** [comment]
@davehun Version `1.2.1` ([see changelog](https://github.com/mattmattmatt/node-red-contrib-yeelight-compat-hue/releases/tag/v1.2.1)) was just released and might solve your issue (in case it still exists). If it doesn't solve the problem, this release should at least give more helpful logging information.

Could you please try to reproduce your issue? And if you still have it, post your full setup, the actions you take to reproduce it, and a full log here? Thank you!

I will close this until then, but please feel free to re-open if this is still a problem.
